
service: serverless-example

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: ap-southeast-2

functions:
  index:
    handler: index.handler
    events:
      - http:
          path: users
          method: get
