service: serverless-example

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${env:ENV}
  region: ${env:REGION}
  timeout: 5
  deploymentBucket:
    name: ${env:DEPLOYMENT_BUCKET}
    serverSideEncryption: AES256
  environment:
    DB_URL: ${env:DB_URL}
    DB_DB: ${env:DB_DB}
    JWT_SECRET: ${env:JWT_SECRET}
    debug: ${env:DEBUG}

plugins:
  - serverless-offline

functions:
  multi-tenant-index:
    handler: multi-tenant/index.handler
    events:
      - http:
          path: v1/account-{tenant}/{parent}/{id}
          method: put
          cors: true
      - http:
          path: v1/account-{tenant}/{parent}
          method: put
          cors: true
      #---------------------------------------
      - http:
          path: v1/account-{tenant}/{parent}
          method: post
          cors: true
      #---------------------------------------
      - http:
          path: v1/account-{tenant}/{parent}/{id}
          method: patch
          cors: true
      #---------------------------------------
      - http:
          path: v1/account-{tenant}/{parent}/{id}/{association}
          method: get
          cors: true
      - http:
          path: v1/account-{tenant}/{parent}/{id}
          method: get
          cors: true
      - http:
          path: v1/account-{tenant}/{parent}
          method: get
          cors: true
      #---------------------------------------
      - http:
          path: v1/account-{tenant}/{parent}/{id}
          method: delete
          cors: true
      #---------------------------------------
      #---------------------------------------
      - http:
          path: v1/{parent}/{id}
          method: put
          cors: true
      - http:
          path: v1/{parent}
          method: put
          cors: true
      #---------------------------------------
      - http:
          path: v1/{parent}
          method: post
          cors: true
      #---------------------------------------
      - http:
          path: v1/{parent}/{id}
          method: patch
          cors: true
      #---------------------------------------
      - http:
          path: v1/{parent}/{id}/{association}
          method: get
          cors: true
      - http:
          path: v1/{parent}/{id}
          method: get
          cors: true
      - http:
          path: v1/{parent}
          method: get
          cors: true
      #---------------------------------------
      - http:
          path: v1/{parent}/{id}
          method: delete
          cors: true
#  single-tenant-index:
#    handler: example/index.handler
#    events:
#      - http:
#          path: v1/{parent}/{id}
#          method: put
#          cors: true
#      - http:
#          path: v1/{parent}
#          method: put
#          cors: true
#      #---------------------------------------
#      - http:
#          path: v1/{parent}
#          method: post
#          cors: true
#      #---------------------------------------
#      - http:
#          path: v1/{parent}/{id}
#          method: patch
#          cors: true
#      #---------------------------------------
#      - http:
#          path: v1/{parent}/{id}/{association}
#          method: get
#          cors: true
#      - http:
#          path: v1/{parent}/{id}
#          method: get
#          cors: true
#      - http:
#          path: v1/{parent}
#          method: get
#          cors: true
#      #---------------------------------------
#      - http:
#          path: v1/{parent}/{id}
#          method: delete
#          cors: true
